### ISSUE TITLE
error on pyw extention

### ISSUE THREAD

**Issue by kucingkembar** [xhlulu/dl-translate#44]
hi, it's me again, sorry again for bad English
I tried this code in py file, open using python IDLE, run -> run module F5 ===> no problem
then rename the extension to pyw, open like exe (double click), and this is the result:
```
Traceback (most recent call last):
  File "D:\Script\translate.pyw", line 67, in FB_Loading
    import dl_translate as dlt
  File "C:\Python\Python39\lib\site-packages\dl_translate\__init__.py", line 3, in <module>
    from ._translation_model import TranslationModel
  File "C:\Python\Python39\lib\site-packages\dl_translate\_translation_model.py", line 5, in <module>
    import transformers
  File "C:\Python\Python39\lib\site-packages\transformers\__init__.py", line 43, in <module>
    from . import dependency_versions_check
  File "C:\Python\Python39\lib\site-packages\transformers\dependency_versions_check.py", line 36, in <module>
    from .file_utils import is_tokenizers_available
  File "C:\Python\Python39\lib\site-packages\transformers\file_utils.py", line 58, in <module>
    logger = logging.get_logger(__name__)  # pylint: disable=invalid-name
  File "C:\Python\Python39\lib\site-packages\transformers\utils\logging.py", line 119, in get_logger
    _configure_library_root_logger()
  File "C:\Python\Python39\lib\site-packages\transformers\utils\logging.py", line 82, in _configure_library_root_logger
    _default_handler.flush = sys.stderr.flush
AttributeError: 'NoneType' object has no attribute 'flush'
```

any guide to fix this?

**Comment by xhlulu** [comment]
I never tested on pyw files and I'm not very familiar, so not sure it's something supported. 

Maybe can you write a simple script that runs 
```
import transformers
print(transformers.__version__)
```

and open in pyw? If that works in py but not pyw then it's likely a transformers issue and you can log a issue there

**Comment by kucingkembar** [comment]
thank you for your reply,
when using idle 
```
import transformers
print(transformers.__version__)
input("press any key to continue...")
```
it shows: 4.12.5

when open as pyw, the window/cmd do not appear,
I think this is the source

I tried to update it using
`pip install --upgrade transformers`
successful to update to 4.15.0
but the  pyw, the window/cmd still do not appear

**Comment by xhlulu** [comment]
In this case I believe this is an issue with the `transformers` library. Feel free to open an issue there: https://github.com/huggingface/transformers

**Comment by kucingkembar** [comment]
thank you again xhlulu for the reply, I close this issue
